name: earth-analytics-python
# referenced https://github.com/albarji/teaching-environments/blob/master/ensembles/environment.yml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver
  - pandas

  # Machine learning
  - scikit-learn
  
  # Spatial packages
  #- rasterio
  - pysal
  - pyproj
  - rasterstats
  - geopy
  - cartopy
  #- geopandas
  - descartes
  - contextily
  - earthpy=0.9.2
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - rioxarray
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask

  # Natural language processing
  #- nltk
  #- textblob

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse
  
  # Autograding
  - matplotcheck>=0.1.2
  - nbgrader
